---
- name: Create databases
  community.mysql.mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: present
    login_unix_socket: "{{ mariadb_socket }}"
  loop: "{{ mariadb_databases }}"
  loop_control:
    label: "{{ item.name }}"
