---
- name: Install MariaDB Python libraries.
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ mariadb_python_package }}"

- name: Install MariaDB Packages
  ansible.builtin.package:
    name: "{{ mariadb_packages }}"
    state: present
  register: mariadb_deb_packages_is_installed
  notify:
    - Service started

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers
