---
- name: Check if Mariadb is already installed.
  ansible.builtin.stat:
    path: /etc/init.d/mysql
  register: mariadb_installed

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when: not mariadb_installed.stat.exists

- name: Install MariaDB Python libraries.
  ansible.builtin.apt:
    name: "{{ mariadb_python_package }}"
    state: present

- name: Install MariaDB Packages
  ansible.builtin.package:
    name: "{{ mariadb_packages }}"
    state: present
  register: mariadb_deb_packages_is_installed
  notify:
    - Service started

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers
