---
- name: Create Users and rights
  community.mysql.mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: present
    login_unix_socket: "{{ mariadb_socket }}"
  loop: "{{ mariadb_users }}"
  when: mariadb_users
  no_log: true
