---
- name: Service started
  ansible.builtin.service:
    name: "{{ mariadb_daemon }}"
    state: started
    enabled: true

- name: Restart MariaDB
  ansible.builtin.service:
    name: "{{ mariadb_daemon }}"
    state: restarted
